version: '3'
services:
  python-app:
    environment:
      - REDIS_DB=0
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - ENVIRONMENT=PROD
      - PORT=8000
      - HOST=localhost
      - PYTHONUNBUFFERED=1
    image: ghcr.io/ujjwalkarn954/tradebyte-devops-challenge
    ports:
      - 80:8000
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
